[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1000000
script = "script"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 64
depth = 128
fail_on_revert = false

# Tron build profile.
# Use:  $env:FOUNDRY_PROFILE="tron"; forge build
[profile.tron]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1000000
script = "script"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true


