[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
train_htlc = "7CWoH7g5BaNswYTnd3pxjvJ5PZaBScHa5CpnVeL8wW4a"

[programs.localnet]
train_htlc = "6zasug6x5AY93zNVjPZPGoqQfdTBd3C1w6CU9NDKtNH8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
