name: Starknet Tests

on:
  push:
    branches: [ main-add-starknet ]
    paths:
      - 'chains/starknet/**'
  pull_request:
    branches: [ main-add-starknet ]
    paths:
      - 'chains/starknet/**'

jobs:
  run-starknet-tests:
    name: Run Starknet Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.14.0"

      - name: Install Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.57.0"

      - name: Build Contracts
        working-directory: chains/starknet
        run: scarb build

      - name: Run Tests
        working-directory: chains/starknet
        run: snforge test
